name: environment-thing

dependencies:
  - python=3.9
  - numpy
  - math
  - matplotlib
  - wolframalpha
  - discord
  - sympy
  - openai
  - pip:
    - git+https://github.com/intrepidbird/intrepidbot.git
